# Setup
title:               Raphaëlle Roffo
tagline:             'Geospatial data science portfolio & training material'
description:         'A space for sharing my projects, research interests and GIS training material. By <a href="https://twitter.com/feili_rf" target="_blank">@feili_rf</a>.'
url:                 https://raphaelle-roffo.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Raphaëlle Roffo
  url:               https://twitter.com/feili_rf
  email:             raphaelle.roffo@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
